### PR TITLE
18 metadata extraction

### PR DESCRIPTION
**Pull request by sbmess2014**
Added content to a number of tests.
Got most of the tests passing.
Addressed most of the 'key not found' panics.

### CODE REVIEW

**Comment by sbmess2014** [comment]
There are a bunch of places where the parse functions return an error that ends up being included as is inside the config structure (if the input yaml config is funny). Would it be better to panic and spit out an error message straight away instead of possibly including something stupid in the generated html output?

**Comment by sbmess2014** [comment]
Ok, I had heard of rustfmt but hadn't got around to trying it yet. 

I can fix the matches up as well but it will be a couple of days before I have some free time to work on it.

**Comment by sbmess2014** [comment]
Do you want me to try to finish off the config test?

**Comment by sbmess2014** [comment]
Ok, all tests are passing but the parse_full_config test isn't complete yet. The following need to be added to the test case:
[ ] fields for series
[ ] templates for layout
[ ] format for date
[ ] feeds
[ ] other content

**Comment by sbmess2014** [comment]
In pure-config.yaml the 'index.html' is under structure/index but in lightning.yaml it is under layout/templates/index. Do you have a preferred location for it or support both? There isn't any code to parse the structure section at the moment but there is some to parse layout.

**Comment by chriskrycho** [comment]
Also, a quick note: I pushed up what changes I had in my repo (which are *old*), and accidentally introduced a merge conflict here – sorry about that. 😞

**Comment by sbmess2014** [comment]
The new code looks a heap better. I was starting to wonder if Serde could do stuff like that.

For the taxonomies, should you be able to specify a set of allowed values? Then should the hierarchies be between different values of a taxonomy or between taxonomies?

I'll leave this alone for a little bit then unless there is something in particular you want me to work on.

**Comment by sbmess2014** [comment]
So, I obviously don't know how to use git...

Should I rebase on top of your last commit on the branch  or something or do I just edit the files until the conflicts disappear?

**Comment by chriskrycho** [comment]
Either way should work, but even with a rebase you're probably going to have to edit the files in the end. 😬 Alas.

**Comment by sbmess2014** [comment]
Conflict fixed 😄

**Comment by chriskrycho** [comment]
This got… lost. Because I never ended up working on this. And now I've pivoted. Thanks again, and I hope this was at least fun or interesting or a good learning pass when you did it!

**Pull request closed without merging**
